spring:
  datasource:
    url: jdbc:h2:mem:ds3
    username: nina
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

api:
  security:
    token:
      secret=${JWT_SECRET:my-secret-key}: